---

################################################################################
#  description: Installs/applies OS updates and patches on DietPi
#  usage: ansible-playbook DietPi_Apply-OS-Updates.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Apply OS updates and patches on DietPi
  hosts: "{{ HostOrGroup|default ('localhost') }}"
  serial: "100%"
  become: true
  gather_facts: False
  tasks:


# apt - Manages apt-packages
# REF: http://docs.ansible.com/ansible/apt_module.html
######################################################

  - name: Update / upgrade all packages
    apt:
      update_cache: yes
      upgrade: full
      autoremove: yes