services:
  duplicati:
    hostname: ${DOCKERHOSTNAME}
    ports:
      - ${DUPLICATI_PORT_8200}:8200
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: ${DUPLICATI_RESTART}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/duplicati:/config
      - ${DOCKERSTORAGEDIR}:/storage
      - ${DUPLICATI_BACKUPSDIR}:/backups
      - ${DUPLICATI_SOURCEDIR}:/source
  handbrake:
    hostname: ${DOCKERHOSTNAME}
    ports:
      - ${HANDBRAKE_PORT_5800}:5800
    image: jlesage/handbrake
    container_name: handbrake
    environment:
      - GROUP_ID=${PGID}
      - USER_ID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: ${HANDBRAKE_RESTART}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/handbrake:/config
      - ${DOCKERSTORAGEDIR}:/storage
      - ${HANDBRAKE_OUTPUTDIR}:/output
      - ${HANDBRAKE_WATCHDIR}:/watch
  logarr:
    hostname: ${DOCKERHOSTNAME}
    ports:
      - ${LOGARR_PORT_80}:80
    image: monitorr/logarr
    container_name: logarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: ${LOGARR_RESTART}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/logarr:/config
      - ${DOCKERCONFDIR}:/var/log/logarrlogs:ro
      - ${DOCKERSTORAGEDIR}:/storage
  nzbget:
    hostname: ${DOCKERHOSTNAME}
    ports:
      - ${NZBGET_PORT_6789}:6789
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: ${NZBGET_RESTART}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/nzbget:/config
      - ${DOCKERSTORAGEDIR}:/storage
  nzbhydra2:
    hostname: ${DOCKERHOSTNAME}
    ports:
      - ${NZBHYDRA2_PORT_5076}:5076
    image: lscr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: ${NZBHYDRA2_RESTART}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/nzbhydra2:/config
      - ${DOCKERSTORAGEDIR}:/storage
  organizr:
    hostname: ${DOCKERHOSTNAME}
    ports:
      - ${ORGANIZR_PORT_80}:80
    image: ghcr.io/organizr/organizr
    container_name: organizr
    environment:
      - branch=${ORGANIZR_BRANCH}
      - fpm=${ORGANIZR_FPM}
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: ${ORGANIZR_RESTART}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/organizr:/config
      - ${DOCKERSTORAGEDIR}:/storage
  plex:
    network_mode: ${PLEX_NETWORK_MODE}
    image: lscr.io/linuxserver/plex
    container_name: plex
    environment:
      - PGID=${PGID}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PUID=${PUID}
      - TZ=${TZ}
      - VERSION=${PLEX_VERSION}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: ${PLEX_RESTART}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/plex:/config
      - ${DOCKERSTORAGEDIR}:/storage
  portainer:
    hostname: ${DOCKERHOSTNAME}
    ports:
      - ${PORTAINER_PORT_9000}:9000
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    environment:
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: ${PORTAINER_RESTART}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERCONFDIR}/portainer:/data
      - ${DOCKERSTORAGEDIR}:/storage
  radarr:
    hostname: ${DOCKERHOSTNAME}
    ports:
      - ${RADARR_PORT_7878}:7878
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: ${RADARR_RESTART}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/radarr:/config
      - ${DOCKERSTORAGEDIR}:/storage
  sonarr:
    hostname: ${DOCKERHOSTNAME}
    ports:
      - ${SONARR_PORT_8989}:8989
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: ${SONARR_RESTART}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/sonarr:/config
      - ${DOCKERSTORAGEDIR}:/storage
  unificontroller:
    hostname: ${DOCKERHOSTNAME}
    ports:
      - ${UNIFICONTROLLER_PORT_10001}:10001/udp
      - ${UNIFICONTROLLER_PORT_3478}:3478/udp
      - ${UNIFICONTROLLER_PORT_6789}:6789
      - ${UNIFICONTROLLER_PORT_8080}:8080
      - ${UNIFICONTROLLER_PORT_8081}:8081
      - ${UNIFICONTROLLER_PORT_8443}:8443
      - ${UNIFICONTROLLER_PORT_8843}:8843
      - ${UNIFICONTROLLER_PORT_8880}:8880
    image: lscr.io/linuxserver/unifi-controller
    container_name: unificontroller
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: ${UNIFICONTROLLER_RESTART}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/unificontroller:/config
      - ${DOCKERSTORAGEDIR}:/storage
  watchtower:
    hostname: ${DOCKERHOSTNAME}
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - REPO_PASS=${WATCHTOWER_REPO_PASS}
      - REPO_USER=${WATCHTOWER_REPO_USER}
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP}
      - WATCHTOWER_INCLUDE_STOPPED=${WATCHTOWER_INCLUDE_STOPPED}
      - WATCHTOWER_MONITOR_ONLY=${WATCHTOWER_MONITOR_ONLY}
      - WATCHTOWER_NOTIFICATION_TEMPLATE=${WATCHTOWER_NOTIFICATION_TEMPLATE}
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL}
      - WATCHTOWER_NOTIFICATIONS_LEVEL=${WATCHTOWER_NOTIFICATIONS_LEVEL}
      - WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATIONS}
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE}
      - WATCHTOWER_TIMEOUT=${WATCHTOWER_TIMEOUT}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: ${WATCHTOWER_RESTART}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERSTORAGEDIR}:/storage
