- name: Copy Brother5430 zip file
  register: copy_results
  ansible.windows.win_copy:
    src: Brother5430D.zip
    dest: C:\Temp\

- name: Extracts Brother 5430 zip file
  community.windows.win_unzip:
    src: C:\Temp\Brother5430D.zip
    dest: C:\Temp\Brother5430D
    delete_archive: no
  when: copy_results.changed == true

- name: Install printer if not present
  register: printer_status
  ansible.windows.win_powershell:
    script: |
      $printerDriverName = 'Brother HL-5340D series'
      $infPath = 'C:\temp\Brother5430D\BROHLA8A.INF'
      $printerName = '\\http://pi4:631\Brother_HL-5340D_series'
      $printerPortName = 'http://pi4:631/printers/Brother_HL-5340D_series'
      
      try {
          $printer = Get-Printer -Name $printerName -ErrorAction Stop
      }
      catch {
          $msg = ('Printer did not exist')
          Throw $msg
      }
      
      if ($printer) {
          $Ansible.Changed = $false
      }
      else {
          pnputil.exe /a $infPath
          try { Add-PrinterDriver -Name $printerDriverName -ErrorAction Stop }
          catch { Add-PrinterDriver -Name $printerDriverName  -ErrorAction Stop  -InfPath $infPath }
      
          Add-Printer -Name $printerName -PortName $printerPortName -DriverName $printerDriverName
          $Ansible.Changed = $true
      }
-  debug:
     msg: "{{ printer_status }}"

- name: Restart print spooler if needed
  win_service:
    name: spooler
    state: restarted
  when: printer_status.changed == true